import { Language, VoiceOption, Emotion } from './types';

const DEFAULT_VOICES: VoiceOption[] = [
  { id: 'Kore', name: 'Female 1', gender: 'Female' },
  { id: 'Zephyr', name: 'Female 2', gender: 'Female' },
  { id: 'Puck', name: 'Male 1', gender: 'Male' },
  { id: 'Charon', name: 'Male 2', gender: 'Male' },
  { id: 'Fenrir', name: 'Male 3', gender: 'Male' },
];

export const VOICES_BY_LANGUAGE: Record<Language, VoiceOption[]> = {
  'English': [
    { id: 'Kore', name: 'Kore (Female)', gender: 'Female' },
    { id: 'Zephyr', name: 'Zephyr (Female)', gender: 'Female' },
    { id: 'Puck', name: 'Puck (Male)', gender: 'Male' },
    { id: 'Charon', name: 'Charon (Male)', gender: 'Male' },
    { id: 'Fenrir', name: 'Fenrir (Male)', gender: 'Male' },
  ],
  'Hindi': [
    { id: 'Kore', name: 'Diya (Female)', gender: 'Female' },
    { id: 'Zephyr', name: 'Anika (Female)', gender: 'Female' },
    { id: 'Kore', name: 'Priya (Female)', gender: 'Female' },
    { id: 'Puck', name: 'Aarav (Male)', gender: 'Male' },
    { id: 'Charon', name: 'Rohan (Male)', gender: 'Male' },
    { id: 'Fenrir', name: 'Vikram (Male)', gender: 'Male' },
    { id: 'Puck', name: 'Kabir (Male)', gender: 'Male' },
    { id: 'Charon', name: 'Arjun (Male)', gender: 'Male' },
    { id: 'Fenrir', name: 'Ishaan (Male)', gender: 'Male' },
    { id: 'Kore', name: 'Aditi (Female)', gender: 'Female' },
    { id: 'Zephyr', name: 'Isha (Female)', gender: 'Female' },
    { id: 'Kore', name: 'Kavya (Female)', gender: 'Female' },
    { id: 'Zephyr', name: 'Mira (Female)', gender: 'Female' },
    { id: 'Kore', name: 'Neha (Female)', gender: 'Female' },
    { id: 'Zephyr', name: 'Riya (Female)', gender: 'Female' },
    { id: 'Kore', name: 'Saanvi (Female)', gender: 'Female' },
    { id: 'Zephyr', name: 'Tara (Female)', gender: 'Female' },
    { id: 'Kore', name: 'Vidya (Female)', gender: 'Female' },
    { id: 'Zephyr', name: 'Zara (Female)', gender: 'Female' },
    { id: 'Puck', name: 'Advik (Male)', gender: 'Male' },
    { id: 'Charon', name: 'Dev (Male)', gender: 'Male' },
    { id: 'Fenrir', name: 'Kian (Male)', gender: 'Male' },
    { id: 'Puck', name: 'Neel (Male)', gender: 'Male' },
    { id: 'Charon', name: 'Om (Male)', gender: 'Male' },
    { id: 'Fenrir', name: 'Parth (Male)', gender: 'Male' },
    { id: 'Puck', name: 'Reyansh (Male)', gender: 'Male' },
    { id: 'Charon', name: 'Samar (Male)', gender: 'Male' },
    { id: 'Fenrir', name: 'Veer (Male)', gender: 'Male' },
    { id: 'Puck', name: 'Vivaan (Male)', gender: 'Male' },
    { id: 'Kore', name: 'Aisha (Female)', gender: 'Female' },
    { id: 'Zephyr', name: 'Bhavna (Female)', gender: 'Female' },
    { id: 'Kore', name: 'Chaya (Female)', gender: 'Female' },
    { id: 'Zephyr', name: 'Deepika (Female)', gender: 'Female' },
    { id: 'Kore', name: 'Esha (Female)', gender: 'Female' },
    { id: 'Zephyr', name: 'Gayatri (Female)', gender: 'Female' },
    { id: 'Kore', name: 'Heena (Female)', gender: 'Female' },
    { id: 'Zephyr', name: 'Jaya (Female)', gender: 'Female' },
    { id: 'Kore', name: 'Lalita (Female)', gender: 'Female' },
    { id: 'Zephyr', name: 'Meena (Female)', gender: 'Female' },
    { id: 'Kore', name: 'Nisha (Female)', gender: 'Female' },
    { id: 'Zephyr', name: 'Pooja (Female)', gender: 'Female' },
    { id: 'Kore', name: 'Radha (Female)', gender: 'Female' },
    { id: 'Zephyr', name: 'Sunita (Female)', gender: 'Female' },
    { id: 'Kore', name: 'Usha (Female)', gender: 'Female' },
    { id: 'Puck', name: 'Anil (Male)', gender: 'Male' },
    { id: 'Charon', name: 'Bharat (Male)', gender: 'Male' },
    { id: 'Fenrir', name: 'Chandan (Male)', gender: 'Male' },
    { id: 'Puck', name: 'Dinesh (Male)', gender: 'Male' },
    { id: 'Charon', name: 'Girish (Male)', gender: 'Male' },
    { id: 'Fenrir', name: 'Harish (Male)', gender: 'Male' },
    { id: 'Puck', name: 'Jitendra (Male)', gender: 'Male' },
    { id: 'Charon', name: 'Karan (Male)', gender: 'Male' },
    { id: 'Fenrir', name: 'Manoj (Male)', gender: 'Male' },
    { id: 'Puck', name: 'Naveen (Male)', gender: 'Male' },
    { id: 'Charon', name: 'Prakash (Male)', gender: 'Male' },
    { id: 'Fenrir', name: 'Rajesh (Male)', gender: 'Male' },
    { id: 'Puck', name: 'Sunil (Male)', gender: 'Male' },
    { id: 'Charon', name: 'Tarun (Male)', gender: 'Male' },
    { id: 'Fenrir', name: 'Vijay (Male)', gender: 'Male' },
    { id: 'Kore', name: 'Ananya (Female)', gender: 'Female' },
    { id: 'Zephyr', name: 'Ishita (Female)', gender: 'Female' },
    { id: 'Kore', name: 'Kiara (Female)', gender: 'Female' },
    { id: 'Zephyr', name: 'Myra (Female)', gender: 'Female' },
    { id: 'Kore', name: 'Navya (Female)', gender: 'Female' },
    { id: 'Puck', name: 'Aryan (Male)', gender: 'Male' },
    { id: 'Charon', name: 'Ishan (Male)', gender: 'Male' },
    { id: 'Fenrir', name: 'Rudra (Male)', gender: 'Male' },
    { id: 'Puck', name: 'Sai (Male)', gender: 'Male' },
    { id: 'Charon', name: 'Shaurya (Male)', gender: 'Male' },
  ],
  'Bengali': DEFAULT_VOICES,
  'Tamil': DEFAULT_VOICES,
  'Telugu': DEFAULT_VOICES,
  'Marathi': DEFAULT_VOICES,
  'Gujarati': DEFAULT_VOICES,
  'Kannada': DEFAULT_VOICES,
  'Malayalam': DEFAULT_VOICES,
  'Odia': DEFAULT_VOICES,
  'Punjabi': DEFAULT_VOICES,
  'Urdu': DEFAULT_VOICES,
  'Assamese': DEFAULT_VOICES,
  'Maithili': DEFAULT_VOICES,
  'Santali': DEFAULT_VOICES,
  'Kashmiri': DEFAULT_VOICES,
  'Nepali': DEFAULT_VOICES,
  'Sindhi': DEFAULT_VOICES,
  'Konkani': DEFAULT_VOICES,
  'Dogri': DEFAULT_VOICES,
  'Manipuri': DEFAULT_VOICES,
  'Bodo': DEFAULT_VOICES,
  'Sanskrit': DEFAULT_VOICES,
  'Chhattisgarhi': DEFAULT_VOICES,
  'Haryanvi': DEFAULT_VOICES,
  'Rajasthani': DEFAULT_VOICES,
};


export const LANGUAGES: Language[] = ['English', 'Hindi', 'Bengali', 'Tamil', 'Telugu', 'Marathi', 'Gujarati', 'Kannada', 'Malayalam', 'Odia', 'Punjabi', 'Urdu', 'Assamese', 'Maithili', 'Santali', 'Kashmiri', 'Nepali', 'Sindhi', 'Konkani', 'Dogri', 'Manipuri', 'Bodo', 'Sanskrit', 'Chhattisgarhi', 'Haryanvi', 'Rajasthani'];

export const EMOTIONS: Emotion[] = ['Default', 'Happy', 'Sad', 'Angry', 'Excited', 'Calm'];

export const EMOTION_PROMPTS: Record<Emotion, string> = {
    'Default': '',
    'Happy': 'Say it in a cheerful and happy tone: ',
    'Sad': 'Say it in a somber and sad tone: ',
    'Angry': 'Say it in an angry and stern tone: ',
    'Excited': 'Say it in an excited and energetic tone: ',
    'Calm': 'Say it in a calm and soothing tone: ',
};

export const PLACEHOLDER_TEXTS: Record<Language, string> = {
    'English': 'Hello! Welcome to the AI Voice Generator. Type any text here to get started.',
    'Hindi': 'नमस्ते! एआई वॉयस जेनरेटर में आपका स्वागत है। आरंभ करने के लिए यहां कोई भी टेक्स्ट टाइप करें।',
    'Bengali': 'নমস্কার! এআই ভয়েস জেনারেটরে আপনাকে স্বাগতম। শুরু করতে এখানে যেকোনো টেক্সট টাইপ করুন।',
    'Tamil': 'வணக்கம்! AI குரல் இயற்றிக்கு வரவேற்கிறோம். தொடங்குவதற்கு இங்கே எந்த உரையையும் தட்டச்சு செய்யவும்.',
    'Telugu': 'నమస్కారం! AI వాయిస్ జెనరేటర్‌కు స్వాగతం. ప్రారంభించడానికి ఇక్కడ ఏదైనా వచనాన్ని టైప్ చేయండి.',
    'Marathi': 'नमस्कार! एआय व्हॉईस जनरेटरमध्ये आपले स्वागत आहे. प्रारंभ करण्यासाठी येथे कोणताही मजकूर टाइप करा.',
    'Gujarati': 'નમસ્તે! AI વોઈસ જનરેટરમાં તમારું સ્વાગત છે. શરૂ કરવા માટે અહીં કોઈપણ ટેક્સ્ટ ટાઇપ કરો.',
    'Kannada': 'ನಮಸ್ಕಾರ! AI ವಾಯ್ಸ್ ಜನರೇಟರ್‌ಗೆ ಸ್ವಾಗತ. ಪ್ರಾರಂಭಿಸಲು ಇಲ್ಲಿ ಯಾವುದೇ ಪಠ್ಯವನ್ನು ಟೈಪ್ ಮಾಡಿ.',
    'Malayalam': 'നമസ്കാരം! AI വോയ്‌സ് ജനറേറ്ററിലേക്ക് സ്വാഗതം. ആരംഭിക്കുന്നതിന് ഇവിടെ ഏതെങ്കിലും വാചകം ടൈപ്പ് ചെയ്യുക.',
    'Odia': 'ନମସ୍କାର! AI ଭଏସ୍ ଜେନେରେଟରକୁ ସ୍ଵାଗତ। ଆରମ୍ଭ କରିବା ପାଇଁ ଏଠାରେ ଯେକୌଣସି ପାଠ୍ୟ ଟାଇପ୍ କରନ୍ତୁ।',
    'Punjabi': 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ! AI ਵੌਇਸ ਜਨਰੇਟਰ ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ। ਸ਼ੁਰੂ ਕਰਨ ਲਈ ਇੱਥੇ ਕੋਈ ਵੀ ਟੈਕਸਟ ਟਾਈਪ ਕਰੋ।',
    'Urdu': 'ہیلو! اے آئی وائس جنریٹر میں خوش آمدید۔ شروع کرنے کے لیے یہاں کوئی بھی متن ٹائپ کریں۔',
    'Assamese': 'নমস্কাৰ! AI ভইচ জেনেৰেটৰলৈ স্বাগতম। আৰম্ভ কৰিবলৈ ইয়াত যিকোনো тексту টাইপ কৰক।',
    'Maithili': 'प्रणाम! एआई वॉयस जेनरेटर मे अहाँक स्वागत अछि। शुरू करबाक लेल एत\' कोनो टेक्स्ट टाइप करू।',
    'Santali': 'ᱡᱚᱦᱟᱨ! AI ᱟᱲᱟᱝ ᱡᱮᱱᱮରେᱴᱚᱨ ᱨᱮ ᱟᱯᱮᱭᱟᱜ ᱥᱟᱹᱜᱩᱱ ᱫᱟᱨᱟᱢ! ᱮᱛᱚᱦᱚᱵ ᱞᱟᱹਗᱤᱫ ᱱᱚᱰᱮ ᱡᱟᱦᱟᱸᱱᱟᱜ ᱜᱮ ᱚᱞ ᱢᱮ።',
    'Kashmiri': 'السلام علیکم! اے آئی وائس جنریٹرس منز چھُ خیر مقدم۔ شروع کرنہٕ خٲطرٕ ہیتھ کینہہ تہِ متن ٹائپ کریو۔',
    'Nepali': 'नमस्ते! एआई भ्वाइस जेनेरेटरमा तपाईंलाई स्वागत छ। सुरु गर्न यहाँ कुनै पनि पाठ टाइप गर्नुहोस्।',
    'Sindhi': 'ڀلي ڪري آيا! AI وائيس جنريٽر ۾ ڀليڪار. شروع ڪرڻ لاءِ هتي ڪو به متن ٽائپ ڪريو.',
    'Konkani': 'देव बरे करूं! एआय व्हॉईস जनरेटरान तुमकां येवकार. सुरू करपाक हांगा खंयचोय मजकूर टायप करात.',
    'Dogri': 'नमस्ते! एआई वायस जनरेटरै च तुंदा स्वागत ऐ। शुरू करने आस्तै इत्थै कोई बी पाठ टाइप करो।',
    'Manipuri': 'খুরমজরি! এআই ভয়েস জেনারেটরদা তরাম্না ওকচরি। হৌগতনবগীদমক মফম অসিদা টেক্সট খরা টাইপ তৌবিয়ু।',
    'Bodo': 'खुलुमबाय! एआई भयेस जेनेरेटरआव नोंखौ बरायबाय। जागायजेन्नो हायो जेरावबो लिरнаनै।',
    'Sanskrit': 'नमो नमः! एआई स्वरजनके स्वागतम्। आरब्धुं अत्र किमपि पाठं लिखन्तु।',
    'Chhattisgarhi': 'राम राम! एआई वॉयस जेनरेटर म आप मन के स्वागत हे। सुरू करे बर इहाँ कुछू भी लिखो।',
    'Haryanvi': 'राम-राम! एआई वॉयस जेनरेटर मैं आपका स्वागत सै। शुरू करण खातिर इहाँ कोई भी टेक्स्ट टाइप करो।',
    'Rajasthani': 'खम्मा घणी! एआई वॉयस जेनरेटर में आपरो स्वागत है। शुरू करण वास्ते अठे कोई भी टेक्स्ट टाइप करो।',
};